/**
 * DLZ table generator (sim-physics). Flies the game missile model (simulateShot's engine) over a grid of
 * shooter altitude × shooter Mach × target aspect × target altitude offset and binary-searches
 *   Rmax: target keeps flying straight at 900 km/h,
 *   Rne:  target turns cold at launch and runs with afterburner,
 * for every missile (fine grid for radar missiles, coarse for IR), then writes src/sim/dlzTables.ts.
 *
 *   TUNE=1 npx vitest run tests/tune/dlz-tables.test.ts            # all missiles
 *   TUNE=1 MISSILES=aim120c,r77 npx vitest run tests/tune/dlz-tables.test.ts   # only some (others kept)
 *
 * Run the model fit first if missileModel.ts changed (see model-fit.test.ts). Takes a few minutes.
 */
import { describe, expect, it } from 'vitest';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import type { MissileId } from '../../src/data/types';
import { MISSILES } from '../../src/data/missiles';
import { DLZ_GRID, findRange, gridTargetAlt } from '../../src/sim/dlz';
import { DLZ_TABLES, type DlzTable } from '../../src/sim/dlzTables';
import { soundSpeed } from '../../src/sim/atmosphere';

const OUT = fileURLToPath(new URL('../../src/sim/dlzTables.ts', import.meta.url));
const ENABLED = process.env.TUNE === '1';
const DT = 1 / 30;
const TOL = 0.012;

function generate(id: MissileId): DlzTable {
  const grid = MISSILES[id].seeker === 'ir' ? DLZ_GRID.ir : DLZ_GRID.radar;
  const vt = DLZ_GRID.refTargetSpeed;
  const rmaxKm: number[] = [], rneKm: number[] = [], tofMax: number[] = [], tofNe: number[] = [];
  let guessMax: number | undefined, guessNe: number | undefined;
  for (const alt of grid.alts) {
    for (const mach of grid.machs) {
      for (const aspectDeg of grid.aspects) {
        for (const off of grid.offsets) {
          const targetAlt = gridTargetAlt(alt, off);
          const base = { missile: id, shooterAlt: alt, shooterMach: mach, targetAlt, targetMach: vt / soundSpeed(targetAlt), aspectDeg };
          const a = findRange(base, 'rmax', { dt: DT, tol: TOL, guess: guessMax });
          const b = findRange(base, 'rne', { dt: DT, tol: TOL, guess: guessNe ?? (a.range ? a.range * 0.4 : undefined) });
          guessMax = a.range || undefined;
          guessNe = b.range || undefined;
          rmaxKm.push(Math.round(a.range / 10) / 100);
          rneKm.push(Math.round(Math.min(b.range, a.range) / 10) / 100);
          tofMax.push(Math.round(a.tof * 10) / 10);
          tofNe.push(Math.round(b.tof * 10) / 10);
        }
        guessMax = undefined; guessNe = undefined;
      }
    }
  }
  const ref = MISSILES[id].ref;
  return {
    alts: grid.alts, machs: grid.machs, aspects: grid.aspects, offsets: grid.offsets, refTargetSpeed: vt,
    ref: { highHeadOnKm: ref.highHeadOnKm, highColdKm: ref.highColdKm, lowHeadOnKm: ref.lowHeadOnKm },
    rmaxKm, rneKm, tofMax, tofNe,
  };
}

function arr(a: number[]): string {
  const rows: string[] = [];
  for (let i = 0; i < a.length; i += 25) rows.push('      ' + a.slice(i, i + 25).join(', ') + ',');
  return '[\n' + rows.join('\n') + '\n    ]';
}

function write(tables: Partial<Record<MissileId, DlzTable>>): void {
  const head = `/**
 * GENERATED by tests/tune/dlz-tables.test.ts (TUNE=1 npx vitest run tests/tune/dlz-tables.test.ts).
 * Do not edit by hand. Launch-zone ranges found by flying the game model (missile.ts) in simulateShot().
 * Generated ${new Date().toISOString().slice(0, 10)}.
 */
import type { MissileId } from '../data/types';

export interface DlzTable {
  /** Grid axes: shooter altitude (m), shooter Mach, target aspect (deg, 0 hot .. 180 cold), target altitude minus shooter altitude (m). */
  alts: number[];
  machs: number[];
  aspects: number[];
  offsets: number[];
  /** Target speed (m/s) used when generating; dlzFor corrects for other target speeds. */
  refTargetSpeed: number;
  /** data/missiles.ts ref ranges at generation time; dlzFor rescales if the data changed since. */
  ref: { highHeadOnKm: number; highColdKm: number; lowHeadOnKm: number };
  /** Flattened [alt][mach][aspect][offset]: ranges in km, times of flight in s. */
  rmaxKm: number[];
  rneKm: number[];
  tofMax: number[];
  tofNe: number[];
}

export const DLZ_TABLES: Partial<Record<MissileId, DlzTable>> = {
`;
  const body = (Object.keys(MISSILES) as MissileId[]).filter(id => tables[id]).map(id => {
    const t = tables[id] as DlzTable;
    return `  ${id}: {
    alts: [${t.alts.join(', ')}],
    machs: [${t.machs.join(', ')}],
    aspects: [${t.aspects.join(', ')}],
    offsets: [${t.offsets.join(', ')}],
    refTargetSpeed: ${t.refTargetSpeed},
    ref: { highHeadOnKm: ${t.ref.highHeadOnKm}, highColdKm: ${t.ref.highColdKm}, lowHeadOnKm: ${t.ref.lowHeadOnKm} },
    rmaxKm: ${arr(t.rmaxKm)},
    rneKm: ${arr(t.rneKm)},
    tofMax: ${arr(t.tofMax)},
    tofNe: ${arr(t.tofNe)},
  },`;
  }).join('\n');
  writeFileSync(OUT, head + body + '\n};\n');
}

describe.runIf(ENABLED)('DLZ tables', () => {
  it('generates src/sim/dlzTables.ts', () => {
    const only = process.env.MISSILES ? (process.env.MISSILES.split(',') as MissileId[]) : null;
    const tables: Partial<Record<MissileId, DlzTable>> = { ...DLZ_TABLES };
    for (const id of Object.keys(MISSILES) as MissileId[]) {
      if (only && !only.includes(id)) continue;
      const t0 = performance.now();
      const t = generate(id);
      tables[id] = t;
      const cells = t.rmaxKm.length;
      const empty = t.rmaxKm.filter(v => v <= 0).length;
      // short-range IR missiles have genuine no-shot cells (low, slow, climbing after a crossing or fleeing target)
      expect(empty).toBeLessThan(cells * (MISSILES[id].seeker === 'ir' ? 0.25 : 0.05));
      console.log(`${id.padEnd(8)} ${cells} cells (${empty} empty) in ${((performance.now() - t0) / 1000).toFixed(1)} s`);
      write(tables); // write as we go so a partial run is not lost
    }
  }, 4 * 3_600_000);
});
